@startuml

class MonoBehaviour {
    + Transform transform
    + void : Start()
    + void : Update()
}

class Transform {
    - Vector3 position
    + Vector3 : GetPosition()
    + void : AddForce(Vector3 force)
}

class Vector3 {
    + float x
    + float y
    + float z
}

abstract Animal {
    void : PlayAnimalSound() 
    
}

class Dog {
   
}

class Pig {
   
}

abstract FriendlyAnimal {

}

abstract HostileAnimal {

}

class Lion {

}

Class Alligator {

}

interface FriendlyAnimalInterface {
    void : Pet()
    void : Feed()
}

interface HostileAnimalInterface {
    void : Fight()
    bool : Scare()
    void : Launch(Vector3 direction, float amount)
}



FriendlyAnimal -up-|> Animal
FriendlyAnimal -up-|> FriendlyAnimalInterface
Dog -up-|> FriendlyAnimal
Pig -up-|> FriendlyAnimal

HostileAnimal -up-|> Animal
HostileAnimal -up-|> HostileAnimalInterface
Lion -up-|> HostileAnimal
Alligator -up-|> HostileAnimal

Animal -up-|> MonoBehaviour
MonoBehaviour -right-> Transform
Transform --> Vector3
HostileAnimalInterface -up-> Vector3

@enduml

